# This is a basic workflow to help you get started with Actions

name: CI/CD BACKEND_DEV

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [dev]
  pull_request:
    branches: [none]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    name: 'Deploy to backend DEV'
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
            Port $PORT
          END
        env:
          SSH_USER: 'ahmed_abdelraouf'
          SSH_PRIVATE_KEY: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcn
            NhAAAAAwEAAQAAAQEAxxhqf0aIJh12AZVxs9cR7W2f6hM+OOeEu5x66uJkD3MZT8GJiEsk
            gEPvD/tU7JP7V2oUvH4ToY9Ls8SrFYHQgXgtmxqNXDWYO8W8RoEzN/9QINgV6SWREiScxA
            pdf9+vItAO363t85o/Rzx5K35MTvRWGlhQjQwvkmXcXpqjAOFWPiZMqOUqr8NzOe4cuIPg
            B5etotLLHPjW5Q+gYoiiEeU4DAd34svBaj9Oivuutz0uAOjpYZed9L66k/l7cOcHZ0VcUw
            6XFRwVFi3GyK42qYM1aZsKvVXT8aA2yFVgsyBrNHzUE/lCc65krVLzrZ2mErgFkyPEzwdZ
            txOyNMv4awAAA8gXgZKgF4GSoAAAAAdzc2gtcnNhAAABAQDHGGp/RogmHXYBlXGz1xHtbZ
            /qEz4454S7nHrq4mQPcxlPwYmISySAQ+8P+1Tsk/tXahS8fhOhj0uzxKsVgdCBeC2bGo1c
            NZg7xbxGgTM3/1Ag2BXpJZESJJzECl1/368i0A7fre3zmj9HPHkrfkxO9FYaWFCNDC+SZd
            xemqMA4VY+Jkyo5Sqvw3M57hy4g+AHl62i0ssc+NblD6BiiKIR5TgMB3fiy8FqP06K+663
            PS4A6Olhl530vrqT+Xtw5wdnRVxTDpcVHBUWLcbIrjapgzVpmwq9VdPxoDbIVWCzIGs0fN
            QT+UJzrmStUvOtnaYSuAWTI8TPB1m3E7I0y/hrAAAAAwEAAQAAAQBsTrgArRn7wiMkEWxd
            bS5vfydzayx6QFhQx3uGs8nDLdYjMSHkZxxgOpSemRdF6+rbTvYg5GVBinagQOjhNlF7XS
            lSK0ujUfSS76rQoBCA8f9hHqwsvScCO7CcZRcgLUtVIOI2hKPh1ZN+6ULxii9w9DKy+kA3
            ut1WQttzC6SJIRbT6h6hid4d4bYielHeqVqL8uPwFQ+lfw8E7Fjr/n6OWM+vCQF981wS7+
            OWq0M/Ow6MiPtnU2MkjkdGoqSsezL0nXp7+Gol4Z44Xueg/KlUtcA/z2Mx6S4lG11xdUX5
            jy/vb+hJ7WUNEtJvFTaLBXED6Us7zcQi0KPZejOQUIgBAAAAgC9UjBb4skTNUiof+7ulH2
            bOC9c0xyd+aWOHPtPX7J1zPcAkyk4j/lEE21koDxpLSV6ERbceZKFI0UTruXcXpuEDh4jF
            PTPHzYy3Y9qPUNV05XWGDxKxfkFXp+QhkFpV14OKz4GFKljjJ6jL5mhE/7zY11na2dEjtJ
            4E6uqaTg+BAAAAgQDoEzjBO1QtRF2SRRlrVl0n3Rv3pHgpBELNoCSoeRZ9eY4MgMoe+aSg
            J12DC+AUPcp4HKmDc6jSaTA/8aDKo2WK4T1hGuJ8ytDyYs7MHpfzfnVOHMDnWv5w/tE7l3
            NkalAirzfS1mzC1Qj20BO1Q4KRHS4cN86X6Duxa6X7ytF9AQAAAIEA257QkxIN4ES15fs7
            i1HQX0MAaGTTyPBsXD9ZrccZM3eSuaIY89+50+zGAKSKfFO4LS1n+6BzA426rvzsEZLiit
            tyk1I7KqUzWlmMiEs3P1aahR3sPYMNmVxD4/pDNr4FJmFA0Do0eP7zyVvxVnteLSmCVcZY
            E6aRPwqsm0DnuWsAAAAQYWhtZWRfYWJkZWxyYW91ZgECAw==
            -----END OPENSSH PRIVATE KEY-----
          SSH_HOST: '34.122.183.132'
          PORT: '22'

      - name: Deploying into server
        run: |
          ssh staging 'cd /home/ahmed_abdelraouf/DEV/BackEnd && git reset --hard && git pull origin dev && npm install && pm2 restart DEV_BE --time && pm2 flush'
      - run: echo "🎉 Deployed successfully."
